// What does a HELD media key actually deliver to a CGEventTap?
//
// The project's comments assert three things about autorepeat that were never
// measured on this hardware: that a held key delivers repeats at all, that the
// repeats are distinguishable from a fresh down, and — the load-bearing one —
// that a down whose up got swallowed leaves "an autorepeat nobody stops". This
// probe settles the first two by observation and gives the third a falsifiable
// number.
//
// Run:  swift scripts/probes/media-key-autorepeat.swift
//
// REQUIRES ACCESSIBILITY. A CGEventTap on NX_SYSDEFINED is refused without it,
// even listen-only. Grant it to the process that RUNS the probe (Terminal /
// iTerm / Xcode), not to Crema: System Settings > Privacy & Security >
// Accessibility. The probe says so and exits if the tap cannot be created.
//
// Listen-only on purpose: this observes, never swallows, so it cannot change
// volume or brightness behaviour while it runs and cannot orphan a key pair.
//
// The layout below is Apple's own, not folklore. IOHIDSystem packs the payload
// as `(flavor << 16) | (eventType << 8) | repeat` and Apple's NX event dumper
// unpacks it as flavor = L[0] >> 16, eventType = (L[0] >> 8) & 0xff,
// repeat = L[0] & 0xff (IOHIDFamily, IOHIDSystem.cpp and
// tools/IOHIDNXEventDescription.c). NSEvent.data1 IS compound.misc.L[0].
//
// What to look for, holding brightness-up (or volume-up) for ~3 seconds:
//
//   1. Do repeat=1 events arrive at all, or only one down and one up?
//   2. Is the first gap ~= InitialKeyRepeat and the rest ~= KeyRepeat (printed
//      at startup, converted to ms)? If yes, the repeats are generated by
//      IOHIDKeyboardFilter inside the HID event system — UPSTREAM of every
//      CGEventTap, cancelled by the physical key-up, which no tap can swallow.
//      That is the measurement that decides whether an orphaned down could
//      leave anything running.
//   3. Does MUTE repeat? The legacy kernel path excluded NX_KEYTYPE_MUTE from
//      repeats; the modern userspace filter's exclusion list names the
//      keyboard-page mute usage but not the consumer-page one. Unresolved on
//      paper — press and hold mute and read the answer here.

import AppKit
import CoreGraphics
import Foundation

// ev_keymap.h NX_KEYTYPE_*; only the flavors this app cares about are named,
// the rest print as their number so nothing is silently dropped.
let flavorNames: [Int: String] = [
    0: "SOUND_UP", 1: "SOUND_DOWN", 2: "BRIGHTNESS_UP", 3: "BRIGHTNESS_DOWN",
    4: "CAPS_LOCK", 6: "POWER", 7: "MUTE", 14: "EJECT",
    16: "PLAY", 17: "NEXT", 18: "PREVIOUS", 19: "FAST", 20: "REWIND",
    21: "ILLUMINATION_UP", 22: "ILLUMINATION_DOWN", 23: "ILLUMINATION_TOGGLE",
]

// NX_KEYDOWN / NX_KEYUP from IOLLEvent.h.
func phaseName(_ eventType: Int) -> String {
    switch eventType {
    case 0x0A: "down"
    case 0x0B: "up  "
    default: String(format: "0x%02X", eventType)
    }
}

let start = Date()
var lastAt: [Int: Date] = [:]  // per flavor, so two keys held at once stay legible
var count = 0

func report(data1: Int, flags: CGEventFlags) {
    let flavor = (data1 & 0xFFFF_0000) >> 16
    let eventType = (data1 & 0xFF00) >> 8
    let repeatByte = data1 & 0xFF

    let now = Date()
    let sinceStart = now.timeIntervalSince(start) * 1000
    let gap = lastAt[flavor].map { now.timeIntervalSince($0) * 1000 }
    lastAt[flavor] = now

    count += 1
    let name = flavorNames[flavor] ?? "flavor \(flavor)"
    let gapText = gap.map { String(format: "%7.1f ms since its last", $0) } ?? "      —"
    let fine = flags.contains(.maskAlternate) && flags.contains(.maskShift) ? "  [opt+shift]" : ""
    print(String(
        format: "%7.0f ms  %-18@ %@  repeat=%d  %@  data1=0x%08X%@",
        sinceStart, name as NSString, phaseName(eventType), repeatByte,
        gapText as NSString, data1, fine as NSString
    ))
}

let callback: CGEventTapCallBack = { _, type, event, _ in
    // A tap the system disables mid-run would silently stop reporting and the
    // probe would read as "no repeats arrived" — the exact false negative this
    // is measuring against. Say it out loud instead.
    if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
        print("!! the system disabled this tap (type \(type.rawValue)); re-enable it and re-run")
        return Unmanaged.passUnretained(event)
    }
    guard type.rawValue == 14,  // NX_SYSDEFINED
          let systemEvent = NSEvent(cgEvent: event),
          systemEvent.subtype.rawValue == 8  // NX_SUBTYPE_AUX_CONTROL_BUTTONS
    else { return Unmanaged.passUnretained(event) }
    report(data1: systemEvent.data1, flags: event.flags)
    return Unmanaged.passUnretained(event)
}

// The user's configured repeat rate, so the measured gaps have something to be
// compared AGAINST. Both defaults are in units of 1/60 s.
let initialTicks = UserDefaults.standard.object(forKey: "InitialKeyRepeat") as? Double ?? 25
let repeatTicks = UserDefaults.standard.object(forKey: "KeyRepeat") as? Double ?? 6
print(String(
    format: "configured key repeat: initial %.0f ticks (%.0f ms), then %.0f ticks (%.0f ms)",
    initialTicks, initialTicks * 1000 / 60, repeatTicks, repeatTicks * 1000 / 60
))

guard let tap = CGEvent.tapCreate(
    tap: .cgSessionEventTap,
    place: .headInsertEventTap,
    options: .listenOnly,
    eventsOfInterest: CGEventMask(1 << 14),
    callback: callback,
    userInfo: nil
) else {
    print("""
    could not create the event tap.

    This needs Accessibility permission for the app that RAN this probe —
    Terminal, iTerm or Xcode, not Crema. System Settings > Privacy & Security >
    Accessibility. Grant it, then run the probe again.
    """)
    exit(1)
}

let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
CFRunLoopAddSource(CFRunLoopGetCurrent(), source, .commonModes)
CGEvent.tapEnable(tap: tap, enable: true)

print("""
listening for 30 s. Hold a brightness key for ~3 s, release, then hold volume-up,
then hold mute. Watch the repeat column and the gap column.
""")

CFRunLoopRunInMode(.defaultMode, 30, false)
print("\n\(count) aux-control events seen.")
